# @package _global_

defaults:
  - robot_base

robot:
  # Observation parameters
  num_bodies: 19
  dof_obs_size: 18
  actions_dim: 18
  lower_body_actions_dim: 10 # Yuanhang
  upper_body_actions_dim: 8 # Yuanhang
  policy_obs_dim: -1 # Jiawei
  critic_obs_dim: -1
  # policy_obs_dim: 45 # Jiawei
  # critic_obs_dim: 238
  # policy_obs_dim: 45 # Jiawei
  # policy_obs_dim: 241 # Jiawei
  # self_obs_max_coords: 298  # ${eval:1+20*(3+6+3+3)-3}

  key_bodies: ["L_leg_ankle_link", "R_leg_ankle_link"]
  contact_bodies: [ "L_leg_ankle_link", "R_leg_ankle_link" ]
  num_feet: 2
  right_foot_name: "R_leg_ankle_link"
  left_foot_name: "L_leg_ankle_link"
  foot_name: "leg_ankle_link"
  knee_name: "leg_knee_link"
  has_torso: True
  torso_name: "base_link"
  has_upper_body_dof: True
  dof_names: ['L_arm_shoulder_pitch_joint', 'L_arm_shoulder_roll_joint', 'L_arm_shoulder_yaw_joint', 'L_arm_elbow_joint', 'L_leg_hip_yaw_joint', 'L_leg_hip_roll_joint',
              'L_leg_hip_pitch_joint', 'L_leg_knee_joint', 'L_leg_ankle_joint', 'R_arm_shoulder_pitch_joint', 'R_arm_shoulder_roll_joint', 'R_arm_shoulder_yaw_joint',
              'R_arm_elbow_joint', 'R_leg_hip_yaw_joint', 'R_leg_hip_roll_joint',
              'R_leg_hip_pitch_joint', 'R_leg_knee_joint', 'R_leg_ankle_joint']
  upper_dof_names: ['L_arm_shoulder_pitch_joint',       'L_arm_shoulder_roll_joint', 'L_arm_shoulder_yaw_joint', 'L_arm_elbow_joint','R_arm_shoulder_pitch_joint', 'R_arm_shoulder_roll_joint', 'R_arm_shoulder_yaw_joint',
              'R_arm_elbow_joint']
  upper_left_arm_dof_names: ['L_arm_shoulder_pitch_joint',       'L_arm_shoulder_roll_joint', 'L_arm_shoulder_yaw_joint', 'L_arm_elbow_joint']
  upper_right_arm_dof_names: ['R_arm_shoulder_pitch_joint', 'R_arm_shoulder_roll_joint', 'R_arm_shoulder_yaw_joint',
              'R_arm_elbow_joint']
  lower_dof_names: ['L_leg_hip_yaw_joint', 'L_leg_hip_roll_joint',
              'L_leg_hip_pitch_joint', 'L_leg_knee_joint', 'L_leg_ankle_joint','R_leg_hip_yaw_joint', 'R_leg_hip_roll_joint',
              'R_leg_hip_pitch_joint', 'R_leg_knee_joint', 'R_leg_ankle_joint']
  waist_dof_names: []
  dof_pos_lower_limit_list: [-2.7, 0, -2.7, -1.8, -0.65, -0.65, 
                             -1.57, 0, -1, -2.7, -2.1, -2.7, -1.8, -1, -1, -1.57, 0, -1]
  dof_pos_upper_limit_list: [2.7, 2.1, 2.7, 1, 1, 1, 
                             0.78, 2.2, 0.75, 2.7, 0, 2.7, 1, 0.65, 0.65, 0.78, 2.2, 0.75]
  dof_vel_limit_list: [12., 12., 12., 12., 14., 14., 14., 14., 12., 12., 12., 12., 12., 12., 12., 14., 14., 14.]
  dof_effort_limit_list: [36.,  36.,  36.,  36.,  90.,  90., 150., 150.,  36.,  36.,  36.,  36., 36.,  90.,  90., 150., 150.,  36.]
  
  # only apply for isaacsim
  dof_armature_list: [0.03, 0.03, 0.03, 0.03, 0.03, 0.03,
                      0.03, 0.03, 0.03, 0.03, 0.03, 0.03,
                      0.03, 0.03, 0.03,
                      0.03, 0.03, 0.03]
  # only apply for isaacsim
  dof_joint_friction_list: [0.03, 0.03, 0.03, 0.03, 0.03, 0.03,
                            0.03, 0.03, 0.03, 0.03, 0.03, 0.03,
                            0.03, 0.03, 0.03,
                            0.03, 0.03, 0.03]

  body_names: [ 'base_link',  'L_arm_shoulder_pitch_Link', 'L_arm_shoulder_roll_Link','L_arm_shoulder_yaw_Link', 'L_arm_elbow_Link', 'L_leg_hip_yaw_link', 'L_leg_hip_roll_link', 'L_leg_hip_pitch_link', 'L_leg_knee_link', 'L_leg_ankle_link', 'R_arm_shoulder_pitch_Link', 'R_arm_shoulder_roll_Link', 'R_arm_shoulder_yaw_Link', 'R_arm_elbow_Link', 'R_leg_hip_yaw_link',  'R_leg_hip_roll_link', 'R_leg_hip_pitch_link', 'R_leg_knee_link', 'R_leg_ankle_link']


  terminate_after_contacts_on : ["base_link", "shoulder", "hip"]
  penalize_contacts_on: ["base_link", "shoulder", "hip"]
  init_state:
    pos: [0.0, 0.0, 0.65] # x,y,z [m]
    rot: [0.0, 0.0, 0.0, 1.0] # x,y,z,w [quat]
    lin_vel: [0.0, 0.0, 0.0]  # x,y,z [m/s]
    ang_vel: [0.0, 0.0, 0.0]  # x,y,z [rad/s]
    default_joint_angles :  # : target angles [rad] when action : 0.0
      L_leg_hip_yaw_joint : 0. 
      L_leg_hip_roll_joint : 0            
      L_leg_hip_pitch_joint : -0.16    
      L_leg_knee_joint : 0.36    
      L_leg_ankle_joint : -0.2  
      R_leg_hip_yaw_joint : 0. 
      R_leg_hip_roll_joint : 0 
      R_leg_hip_pitch_joint : -0.16                                    
      R_leg_knee_joint : 0.36                                          
      R_leg_ankle_joint : -0.2                                  
      # torso_joint : 0. 
      L_arm_shoulder_pitch_joint : 0. 
      L_arm_shoulder_roll_joint : 0 
      L_arm_shoulder_yaw_joint : 0.
      L_arm_elbow_joint  : 0.
      R_arm_shoulder_pitch_joint : 0.
      R_arm_shoulder_roll_joint : 0.0
      R_arm_shoulder_yaw_joint : 0.
      R_arm_elbow_joint : 0.



  randomize_link_body_names: [
    'base_link', 'L_leg_hip_yaw_link', 'L_leg_hip_roll_link', 'L_leg_hip_pitch_link', 'L_leg_knee_link',
    'R_leg_hip_yaw_link', 'R_leg_hip_roll_link', 'R_leg_hip_pitch_link', 'R_leg_knee_link',
  ]

  control:
    control_type: P
    # PD Drive parameters:
    stiffness: # [N*m/rad]
      hip_yaw: 100
      hip_roll: 100
      hip_pitch: 100
      knee: 200
      ankle: 20
      shoulder_pitch: 90
      shoulder_roll: 60
      shoulder_yaw: 20
      elbow: 60
      # hip_yaw: 60
      # hip_roll: 60
      # hip_pitch: 60
      # knee: 150
      # ankle: 20
      # shoulder_pitch: 60
      # shoulder_roll: 45
      # shoulder_yaw: 10
      # elbow: 40



    damping: # [N*m/rad]  # [N*m*s/rad]
      hip_yaw: 2.5
      hip_roll: 2.5
      hip_pitch: 2.5
      # knee: 5.0
      knee: 3.5
      ankle: 0.1
      shoulder_pitch: 2.0
      shoulder_roll: 1.0
      shoulder_yaw: 0.4
      elbow: 1.0

    # action scale: target angle = actionScale * action + defaultAngle
    action_scale: 0.25
    action_clip_value: 100.0
    clip_torques: True

  asset:
    collapse_fixed_joints: True # merge bodies connected by fixed joints. Specific fixed joints can be kept by adding " <... dont_collapse="true">
    replace_cylinder_with_capsule: True
    flip_visual_attachments: False
    armature: 0.001 # isaacgym armature is set by this
    thickness: 0.01
    max_angular_velocity: 1000.
    max_linear_velocity: 1000.
    density: 0.001
    angular_damping: 0.
    linear_damping: 0.

    urdf_file: "N2/urdf/${robot.asset.robot_type}.urdf"
    usd_file: "N2/urdf/N2/${robot.asset.robot_type}.usd"
    xml_file: "N2/mjcf/${robot.asset.robot_type}.xml"
    # xml_file: "g1/${robot.asset.robot_type}_fitmotionONLY.xml"
    robot_type: N2
    self_collisions: 0 # 1 to disable, 0 to enable self collisions
    default_dof_drive_mode: 3

    fix_base_link: False # TEST: fix base link to world

  motion:
    motion_lib_type: 'WJX'
    motion_file : ???
    # motion_file : 'humanoidverse/data/motions/g1_29dof/v1/singles/0-ACCAD_Male2General_c3d_A6- Box lift_poses.pkl'
    asset:
      assetRoot: "description/robots/N2/"
      # assetFileName: "g1_29dof_anneal_23dof.xml"
      assetFileName: "mjcf/N2.xml"

    humanoid_type: N2
    bias_offset: False
    has_self_collision: True
    has_mesh: False
    has_jt_limit: False
    has_dof_subset: True
    has_upright_start: True
    has_smpl_pd_offset: False
    remove_toe: False # For humanoid's geom toe
    motion_sym_loss: False
    sym_loss_coef: 1
    big_ankle: True

    has_shape_obs: false
    has_shape_obs_disc: false
    has_shape_variation: False

    masterfoot: False
    freeze_toe: false
    freeze_hand: False
    box_body: True
    real_weight: True
    real_weight_porpotion_capsules: True
    real_weight_porpotion_boxes: True

    body_names:  [ 'base_link',  'L_arm_shoulder_pitch_Link', 'L_arm_shoulder_roll_Link','L_arm_shoulder_yaw_Link', 'L_arm_elbow_Link', 'L_leg_hip_yaw_link', 'L_leg_hip_roll_link', 'L_leg_hip_pitch_link', 'L_leg_knee_link', 'L_leg_ankle_link', 'R_arm_shoulder_pitch_Link', 'R_arm_shoulder_roll_Link', 'R_arm_shoulder_yaw_Link', 'R_arm_elbow_Link', 'R_leg_hip_yaw_link',  'R_leg_hip_roll_link', 'R_leg_hip_pitch_link', 'R_leg_knee_link', 'R_leg_ankle_link']
          
    limb_weight_group: 
      - ['L_leg_hip_yaw_link', 'L_leg_hip_roll_link', 'L_leg_hip_pitch_link', 'L_leg_knee_link', 'L_leg_ankle_link']
      - ['R_leg_hip_yaw_link',  'R_leg_hip_roll_link', 'R_leg_hip_pitch_link', 'R_leg_knee_link', 'R_leg_ankle_link']
      - ['base_link']
      - ['L_arm_shoulder_pitch_Link', 'L_arm_shoulder_roll_Link','L_arm_shoulder_yaw_Link', 'L_arm_elbow_Link']
      - ['R_arm_shoulder_pitch_Link', 'R_arm_shoulder_roll_Link', 'R_arm_shoulder_yaw_Link', 'R_arm_elbow_Link']

    dof_names: ['L_arm_shoulder_pitch_joint', 'L_arm_shoulder_roll_joint', 'L_arm_shoulder_yaw_joint', 'L_arm_elbow_joint', 'L_leg_hip_yaw_joint', 'L_leg_hip_roll_joint',
              'L_leg_hip_pitch_joint', 'L_leg_knee_joint', 'L_leg_ankle_joint', 'R_arm_shoulder_pitch_joint', 'R_arm_shoulder_roll_joint', 'R_arm_shoulder_yaw_joint',
              'R_arm_elbow_joint', 'R_leg_hip_yaw_joint', 'R_leg_hip_roll_joint',
              'R_leg_hip_pitch_joint', 'R_leg_knee_joint', 'R_leg_ankle_joint']
    right_foot_name: "R_leg_ankle_link"
    left_foot_name: "L_leg_ankle_link"


    nums_extend_bodies: 3
    extend_config:
      - joint_name: "left_hand_link"
        parent_name: "L_arm_elbow_Link"
        pos: [-0.0045, 0.00036368, -0.1815]
        rot: [1.0, 0.0, 0.0, 0.0] # w x y z
      - joint_name: "right_hand_link"
        parent_name: "R_arm_elbow_Link"
        pos: [-0.0045, 0.00036368, -0.1815]
        rot: [1.0, 0.0, 0.0, 0.0] # w x y z
      - joint_name: "head_link"
        parent_name: "base_link"
        pos: [0.0, 0.0, 0.42]
        rot: [1.0, 0.0, 0.0, 0.0] # w x y z


    motion_tracking_link:
      - "left_hand_link"
      - "right_hand_link"
      - "head_link"

    lower_body_link:
      - "base_link"
      - "L_leg_hip_yaw_link"
      - "L_leg_hip_roll_link"
      - "L_leg_hip_pitch_link"
      - "L_leg_knee_link"
      - "L_leg_ankle_link"
      - "R_leg_hip_yaw_link"
      - "R_leg_hip_roll_link"
      - "R_leg_hip_pitch_link"
      - "R_leg_knee_link"
      - "R_leg_ankle_link"

    upper_body_link:
      - "L_arm_shoulder_pitch_Link"
      - "L_arm_shoulder_roll_Link"
      - "L_arm_shoulder_yaw_Link"
      - "L_arm_elbow_Link"
      - "R_arm_shoulder_pitch_Link"
      - "R_arm_shoulder_roll_Link"
      - "R_arm_shoulder_yaw_Link"
      - "R_arm_elbow_Link"
      - "left_hand_link"
      - "right_hand_link"
      - "head_link"


    pelvis_link: "base_link"
    base_link: "base_link"
    hips_link:
      - "L_leg_hip_yaw_link"
      - "L_leg_hip_roll_link"
      - "L_leg_hip_pitch_link"
      - "R_leg_hip_yaw_link"
      - "R_leg_hip_roll_link"
      - "R_leg_hip_pitch_link"
    
    joint_matches:
      - ["base_link", "Pelvis"]
      - ["L_leg_hip_pitch_link", "L_Hip"]
      - ["L_leg_knee_link", "L_Knee"]
      - ["L_leg_ankle_link", "L_Ankle"]
      - ["R_leg_knee_link", "R_Hip"]
      - ["right_knee_link", "R_Knee"]
      - ["R_leg_ankle_link", "R_Ankle"]
      - ["L_arm_shoulder_roll_Link", "L_Shoulder"]
      - ["L_arm_elbow_Link", "L_Elbow"]
      - ["left_hand_link", "L_Hand"]
      - ["R_arm_shoulder_roll_Link", "R_Shoulder"]
      - ["R_arm_elbow_Link", "R_Elbow"]
      - ["right_hand_link", "R_Hand"]
      - ["head_link", "Head"]


    smpl_pose_modifier:
      - Pelvis: "[np.pi/2, 0, np.pi/2]"
      - L_Shoulder: "[0, 0, -np.pi/2]"
      - R_Shoulder: "[0, 0, np.pi/2]"

    visualization:
      customize_color : True
      marker_joint_colors : 
      - [0.929, 0.867, 0.437] # pelvis
      - [0.929, 0.867, 0.437] # left_hip_yaw_joint
      - [0.929, 0.867, 0.437] # left_hip_roll_joint
      - [0.929, 0.867, 0.437] # left_hip_pitch_joint
      - [0.929, 0.867, 0.437] # left_knee_joint
      - [0.929, 0.867, 0.437] # left_ankle_pitch_joint
      # - [0.929, 0.867, 0.437] # left_ankle_roll_joint
      - [0.929, 0.867, 0.437] # right_hip_yaw_joint
      - [0.929, 0.867, 0.437] # right_hip_roll_joint
      - [0.929, 0.867, 0.437] # right_hip_pitch_joint
      - [0.929, 0.867, 0.437] # right_knee_joint
      - [0.929, 0.867, 0.437] # right_ankle_pitch_joint
      # - [0.929, 0.867, 0.437] # right_ankle_roll_joint
      # - [0.929, 0.867, 0.437] # waist_yaw_joint
      # - [0.929, 0.867, 0.437] # waist_roll_joint
      # - [0.929, 0.867, 0.437] # torso_joint (waist_pitch_link)
      - [0.929, 0.867, 0.437] # left_shoulder_pitch_joint
      - [0.929, 0.867, 0.437] # left_shoulder_roll_joint
      - [0.929, 0.867, 0.437] # left_shoulder_yaw_joint
      - [0.929, 0.867, 0.437] # left_elbow_joint
      - [0.929, 0.867, 0.437] # right_shoulder_pitch_joint
      - [0.929, 0.867, 0.437] # right_shoulder_roll_joint
      - [0.929, 0.867, 0.437] # right_shoulder_yaw_joint
      - [0.929, 0.867, 0.437] # right_elbow_joint
      - [0, 0.351, 0.613] # left_elbow_joint_extend
      - [0, 0.351, 0.613] # right_elbow_joint_extend
      - [0, 0.351, 0.613] # head_link

# Override motion lib default to use the adapted H1 variant
# motion_lib:
#   _target_: phys_anim.utils.motion_lib_h1.H1_MotionLib

# Override simulation config to use the adapted H1 variant
# env:
#   config:
#     simulator:
#       sim:
#         fps: 200 # 1/dt , dt = 0.005
#         control_freq_inv: 4  # decimation
#         substeps: 1

